export const USER_SIGNUP_PENDING = 'USER_SIGNUP_PENDING';

export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';

export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';

export const USER_SIGNIN_PENDING = 'USER_SIGNIN_PENDING';

export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';

export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';

export const USER_NOT_SIGNEDIN = 'USER_NOT_SIGNEDIN'

export const USER_SIGNEDIN = 'USER_SIGNEDIN'

export const USER_EDITPROFILE_PENDING = 'USER_EDITPROFILE_PENDING';

export const USER_EDITPROFILE_SUCCESS = 'USER_EDITPROFILE_SUCCESS';

export const USER_EDITPROFILE_FAILED = 'USER_EDITPROFILE_FAILED';

